### ISSUE TITLE
Repository management

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/handbook#112]
Now that there are multiple people merging pull requests, closing issues and tagging releases, I think it's a good time to codify some repository management standards.

This document should include detail on:

* [x] Labeling #16 
* [x] Tagging releases / release note format.
* [x] Milestone usage.
* [x] Versioning.

**Comment by miya0001** [comment]
Some questions I came up with:

* [ ] How is the version number decided. Is it semantic versioning, right?
* [ ] Who should add milestone? When is the milestone decided?
* [ ] The workflow of the merge process. How to review? Who should merge?
* [ ] The workflow of the release process.
