### ISSUE TITLE
Identify best practices for closing a pull request

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/handbook#147]
Sometimes, a pull request submitted by a new contributor needs to be closed for one reason or another. _How_ the committer communicates the closure can strongly influence whether the contributor feels positive or negative about the experience.

We should identify some best practices for closing a pull request and document them in the handbook. I'm undecided as to whether "Code review" or "Repository management" is the best place for this; open to suggestions.

**Comment by schlessera** [comment]
I think that closing a PR would happen _instead_ of a code review most of the time, so in my head, "Repository management" makes more sense.
