### ISSUE TITLE
Short descriptions should match WP PHP documentation standard

### ISSUE THREAD

**Issue by schlessera** [wp-cli/handbook#150]
Command short descriptions should match WordPress PHP documentation standard:
https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#meta-language-packs

The documenation guidelines need to be adapted:
https://make.wordpress.org/cli/handbook/documentation-standards/#command-annotation

**Comment by danielbachhuber** [comment]
Related https://github.com/wp-cli/wp-cli/issues/4542

**Comment by danielbachhuber** [comment]
Closing in favor of https://github.com/wp-cli/wp-cli/issues/4542
