### ISSUE TITLE
Add documentation for the lack of support of internationalization

### ISSUE THREAD

**Issue by renatonascalves** [wp-cli/handbook#193]
It came to my understanding recently that WP-CLI does not translate its strings. I'd recommend adding this to the documentation.

While trying to confirm it, I looked at it and could not find any information. Someone was kind to show me this feedback: https://wordpress.slack.com/archives/C02RP4T41/p1511796963000358

**Comment by danielbachhuber** [comment]
> I'd recommend adding this to the documentation.

@renatonascalves Do you have a suggested place to include this?

**Comment by renatonascalves** [comment]
@danielbachhuber Actually, I'm not sure where the best place is. :/
