### ISSUE TITLE
Add LICENCE file

### ISSUE THREAD

**Issue by kirtangajjar** [wp-cli/handbook#216]
Currently the handbook repo does not have any license. I guess MIT should work in this case but I'm not sure as this doc is hosted on make.wordpress.org which may or may not have a policy of having all code in GPL.

**Comment by danielbachhuber** [comment]
> I'm not sure as this doc is hosted on make.wordpress.org which may or may not have a policy of having all code in GPL.

MIT license is GPL-compatible. The historical origins of the handbook repo is the website repo, which is now 6 years old. I think it's safest to go with MIT.
