### ISSUE TITLE
Add documentation for the `--foo[=<bar>]` syntax

### ISSUE THREAD

**Issue by schlessera** [wp-cli/handbook#227]
If you want to provide a flag that can *optionally* include a value, the syntax is `--foo[=<bar>]`.

If you want to make that flag with an optional value entirely *optional* as well, the syntax is `[--foo[=<bar>]]`.

This needs to be documented in the command cookbook.

**Comment by swissspidy** [comment]
I thought it's `[--foo[=<bar>]]` 🙂

See https://wordpress.slack.com/archives/C02RP4T41/p1525867354000141

**Comment by schlessera** [comment]
@swissspidy Adapted the description to include both.

**Comment by spicecadet** [comment]
Created pull request: https://github.com/wp-cli/handbook/pull/293
