### ISSUE TITLE
Update docs for installing wp-cli via homebrew

### ISSUE THREAD

**Issue by obenland** [wp-cli/handbook#234]
From https://meta.trac.wordpress.org/ticket/3629:

https://make.wordpress.org/cli/handbook/installing/#installing-via-homebrew

The following command no longer works as homebrew/php is now deprecated:
`brew install homebrew/php/wp-cli`
WP-CLI can now be installed simply with:
`brew install wp-cli`
Link to formula also needs updating.

**Comment by schlessera** [comment]
Thanks for moving the issue into GitHub, @obenland!
