### ISSUE TITLE
Update Composer and Git installing instructions

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/handbook#246]
We have some Composer and Git installation instructions that are now out of date:

* https://make.wordpress.org/cli/handbook/installing/#installing-via-composer
* https://make.wordpress.org/cli/handbook/pull-requests/#setting-up

Notably, I had an existing `git@github.com:wp-cli/wp-cli.git` checkout that lost all of its commands when I ran `composer update`.

**Comment by schlessera** [comment]
> Notably, I had an existing git@github.com:wp-cli/wp-cli.git checkout that lost all of its commands when I ran composer update.

Is that simply because the `wp-cli/wp-cli` is now the framework only, and not the bundle anymore, or was anything else happening there?

**Comment by danielbachhuber** [comment]
> Is that simply because the `wp-cli/wp-cli` is now the framework only, and not the bundle anymore

Yes, I think this was the extent of it.

**Comment by schlessera** [comment]
Done via #251 and #265
