### ISSUE TITLE
Please add Savvii.com to the hosting list

### ISSUE THREAD

**Issue by ghovens** [wp-cli/handbook#264]
Hi,

We support WP-CLI on all our VPS plans.

https://www.savvii.com

Thanks!

**Comment by ghovens** [comment]
Sorry, will do.

Thanks for the quick reply.

Kind regards,

Gijs

Van: Pascal Birchler <notifications@github.com>
Verzonden: vrijdag 7 december 2018 23:25
Aan: wp-cli/handbook <handbook@noreply.github.com>
CC: Gijs Hovens | Savvii B.V. <gijs@savvii.com>; Author <author@noreply.github.com>
Onderwerp: Re: [wp-cli/handbook] Please add Savvii.com to the hosting list (#264)


Would you mind creating a pull request to add the link? 🙂 Basically like #261<https://github.com/wp-cli/handbook/pull/261> or #258<https://github.com/wp-cli/handbook/pull/258>.

**Comment by danielbachhuber** [comment]
Created a PR in #267
