### ISSUE TITLE
Common Issues Doc - Memory Limit example typo

### ISSUE THREAD

**Issue by raquelmsmith** [wp-cli/handbook#28]
Regarding the common problem _[PHP Fatal error: Allowed memory size of 999999 bytes exhausted](https://make.wordpress.org/cli/handbook/common-issues/#php-fatal-error-allowed-memory-size-of-999999-bytes-exhausted-tried-to-allocate-99-bytes)._ 

The first example (editing the php.ini file) changes the `memory_limit` to 512M. However, the second example for setting the `memory_limit` on the fly temporarily changes it to 256M. For my server, this was not sufficient - I needed to set it to 512M as suggested in the previous example. So, I am thinking this may be a typo in the docs and that those troubleshooting this issue may have more success with 512M.

I can create a pull request for the issue but I'm not 100% I'm not sure if this is something that does need fixing, so I decided to start with creating an issue :)

**Comment by danielbachhuber** [comment]
> I needed to set it to 512M as suggested in the previous example. So, I am thinking this may be a typo in the docs and that those troubleshooting this issue may have more success with 512M.

Pull request welcome!
