### ISSUE TITLE
Add D9 Hosting to hosting providers list

### ISSUE THREAD

**Issue by D9Dan** [wp-cli/handbook#281]
Would it be possible to add D9 Hosting (https://d9.hosting) to the list of hosting providers.

WP-CLI is now available on all hosting plans:

https://d9.hosting/blog/wp-cli-install-wordpress-from-the-command-line/

Thanks!

**Comment by schlessera** [comment]
Sure. Please add a pull request against this file: https://github.com/wp-cli/handbook/blob/master/hosting-companies.md

**Comment by schlessera** [comment]
Fixed via #283
