### ISSUE TITLE
Details of how to update your $PATH for remote execution are incorrect - I think

### ISSUE THREAD

**Issue by rosswintle** [wp-cli/handbook#289]
I believe the section on "Making WP-CLI accessible on a remote server" in the instructions for how to run commands remotely is incorrect.

In `running-commands-remotely.md` (and [here](https://make.wordpress.org/cli/handbook/running-commands-remotely/#making-wp-cli-accessible-on-a-remote-server)) it says:

> If `$HOME/bin` is not already in your path, then you can define it in `~/.bash_profile` or `.profile`

However, from what I understand, `.profile` files are only run for "login shells" and not for remotely executed commands using ssh. The path update should be done in `.bashrc` or equivalent.

Can someone please:

* Confirm this understanding?
* If I'm correct, update the docs to reflect the proper files that needs updating?

Thanks

**Comment by schlessera** [comment]
@rosswintle Yes, you are correct, this is a mistake in the documentation.

Do you want to provide a PR for this (otherwise I'll do it)?
