### ISSUE TITLE
Add `WP_CLI_CUSTOM_SHELL` to list of known environment variables

### ISSUE THREAD

**Issue by schlessera** [wp-cli/handbook#291]
The PR https://github.com/wp-cli/shell-command/pull/33 added a new environment variable `WP_CLI_CUSTOM_SHELL` which allows the user to override the default `/bin/bash` shell used.

This should be documented in https://github.com/wp-cli/handbook/blob/master/config.md#environment-variables .

**Comment by spicecadet** [comment]
Created pull request: https://github.com/wp-cli/handbook/pull/292
