### ISSUE TITLE
How to Set Up wp-cli-dev

### ISSUE THREAD

**Issue by tedsecretsource** [wp-cli/handbook#356]
## How to Set Up wp-cli-dev for wp-cli Development

- [x ] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Clarify the Process for Setting up a Local wp-cli Development Environment**

The attached files are a lightly edited transcript of [a Slack conversation](https://wordpress.slack.com/archives/C02RP4T41/p1589988103314400) in which @schlessera describes how to set up a local dev environment. The idea is that this will form a stub for a section on this topic in the handbook.
![generated_package_structure](https://user-images.githubusercontent.com/28703641/82658287-a508f100-9c1e-11ea-9112-98e79f70c850.png)
[README.md.txt](https://github.com/wp-cli/handbook/files/4667450/README.md.txt)
![vendor_wp_cli_folder_structure](https://user-images.githubusercontent.com/28703641/82658327-b5b96700-9c1e-11ea-8ae6-4f54cf3f11ad.png)

**Comment by danielbachhuber** [comment]
We have some setup instructions going here: https://github.com/wp-cli/wp-cli-dev#installation
