### ISSUE TITLE
Dead links in docu, ends up with 404!

### ISSUE THREAD

**Issue by PontusTideman** [wp-cli/handbook#366]
How often does it syncs?! Because [https://developer.wordpress.org/cli/commands/package/](https://developer.wordpress.org/cli/commands/package/) is edited about 8 months back with correct link, but the link for the cockbook on developer.wordpress.org still leads to [http://wp-cli.org/docs/commands-cookbook/](http://wp-cli.org/docs/commands-cookbook/).

Same on this site [http://wp-cli.org/package-index/](http://wp-cli.org/package-index/), the link for the cookbook is ending up in a 404.

Is all docs synced?
`Much of the WP-CLI documentation (command pages, etc.) is editable through wp-cli/handbook, and then synced to WordPress.org. The WP-CLI.org homepage is hosted on GitHub Pages.`

But the first page is with correct link, but not synced?

**Comment by schlessera** [comment]
Thanks for the report!

This will be fixed once v2.5.0 is released, which will trigger a rebuild of the handbook.

In general, the handbook is kept in sync with the codebase of the latest stable release. Usually this means it is refreshed about every 3-4 months, but the last development cycle was much lower from v2.4.0 to v2.5.0.

Closing this issue, as it will be automatically resolved shortly (v2.5.0 is mostly ready now).
