### ISSUE TITLE
wrong anchor at https://wp-cli.org/de/#installing

### ISSUE THREAD

**Issue by DanielRuf** [wp-cli/handbook#386]
## Bug Report

I am not sure if this is the correct place to report this but the link at https://wp-cli.org/de/#installing does not work but at https://wp-cli.org/#installing due to a wrong anchor in the html code.

Where can I find the website content to provide a PR to fix this issue?

**Comment by SteenSchutt** [comment]
I think this is the file and repository you are looking for :)
https://github.com/wp-cli/wp-cli.github.com/blob/master/de/index.md

**Comment by DanielRuf** [comment]
Thanks, I will open a PR there and close this issue here.

**Comment by DanielRuf** [comment]
Ah, ther was someone faster than me =)
https://github.com/wp-cli/wp-cli.github.com/pull/415
