### ISSUE TITLE
How to connect with remote docker container

### ISSUE THREAD

**Issue by renzit** [wp-cli/handbook#391]
HI,

I need support regarding wp ssh connections.

Is it possible to connect with a remote docker container? how would you make it?

I had an ec2 instance user@192.168.
there I have a runing container with wordpress.

I need to run some operations with wp-cli, I wonder if that would be possible with the --ssh flag?

**Comment by danielbachhuber** [comment]
Closing in favor of https://github.com/wp-cli/wp-cli/discussions/5674
