### ISSUE TITLE
Dash docset won't build a new version - handbook not tagged since v2.2

### ISSUE THREAD

**Issue by rosswintle** [wp-cli/handbook#402]
## Feature Request

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

My colleage is writing an article about WP-CLI and wanted to reference the Dash Docs docset for it but they are out of date, referring only to v2.2 at the most.

There is a [dashdocs generator](https://github.com/wp-cli/dash-docset-generator) but it looks like this is only generating docsets up to version 2.2 because this is the last tagged version of the handbook.

**Describe the solution you'd like**

Could we tag a version 2.6 of the handbook? Is there a good reason not to do this?

Thanks

**Comment by schlessera** [comment]
Thanks for the report, @rosswintle .

I added tags for the missing releases:
![wp-cli_handbook_ __ Complete documentation for WP-CLI - Google Chrome 2022-02-02 at 10 22 46 AM](https://user-images.githubusercontent.com/83631/152194245-2c685559-1216-452f-835e-8392f4d8ba88.jpeg)

**Comment by rosswintle** [comment]
Argh. Sorry, @schlessera - looks like they have to be releases, not just tags. My fault for not diving the source code on the generator in enough detail. Can we do a release as well?

Thank you!

**Comment by rosswintle** [comment]
Awesome. Thanks. I have a good build so will try and submit an update.
