### ISSUE TITLE
Change github MASTER links to MAIN in the handbook

### ISSUE THREAD

**Issue by stefanpejcic** [wp-cli/handbook#409]
https://github.com/github/renaming

Master is replaced with main, so all links should be changed, for example:

- current:
https://github.com/wp-cli/handbook/edit/master/hosting-companies.md

- should be:
https://github.com/wp-cli/handbook/edit/main/hosting-companies.md

**Comment by danielbachhuber** [comment]
These links are now fixed 🐛 🔨
