### ISSUE TITLE
`--context` option not documented

### ISSUE THREAD

**Issue by siliconforks** [wp-cli/handbook#463]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

If you run `wp help`, the "GLOBAL PARAMETERS" section lists a `--context=<context>` option, but this option is not documented in the ["Config" section of the handbook](https://make.wordpress.org/cli/handbook/references/config/).

**Describe how other contributors can replicate this bug**

Simply run `wp help` - every option listed there is documented in the "Config" section of the handbook except for `--context`.

**Describe what you would expect as the correct outcome**

I would expect that the list of options in the handbook should match the options listed with `wp help`.  This is already the case for every option except for the `--context` option.

Possibly there is some reason that the `--context` option is not documented - perhaps it's considered experimental and subject to change?  In that case I still think it would be better just to state that in the documentation instead of leaving it undocumented.

**Let us know what environment you are running this on**

```
OS:     Linux 6.2.0-34-generic #34~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 13:12:03 UTC 2 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php8.1
PHP version:    8.1.2-1ubuntu2.14
php.ini used:   /etc/php/8.1/cli/php.ini
MySQL binary:   /usr/bin/mysql
MySQL version:  mysql  Ver 8.0.34-0ubuntu0.22.04.1 for Linux on x86_64 ((Ubuntu))
SQL modes:
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /home/u
WP-CLI packages dir:
WP-CLI cache dir:       /home/u/.wp-cli/cache
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.8.1
```

**Provide a possible solution**

Probably the documentation for `--context` could be copied from the [WP-CLI v2.6.0 Release Notes](https://make.wordpress.org/cli/2022/01/26/wp-cli-v2-6-0-release-notes/).

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @siliconforks !

I agree that it would be helpful to document the `--context` global argument. Feel free to submit a PR, if you'd like.
