### ISSUE TITLE
Add note about `wp admin` being a separate package

### ISSUE THREAD

**Issue by hirasso** [wp-cli/handbook#479]
## Feature Request

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

The [page about `wp admin`](https://developer.wordpress.org/cli/commands/admin/) only documents the command, but running `wp admin` won't work without first installing the command.

**Describe the solution you'd like**

The page could provide a hint that the command needs to be installed separately, as described here:  https://github.com/wp-cli/admin-command/

**Comment by hirasso** [comment]
Suggestion: 

This command must be installed before you can use it: https://github.com/wp-cli/admin-command/?tab=readme-ov-file#installing

If that wording looks good to the maintainers, I'd happily create a PR :)

**Comment by swissspidy** [comment]
There's already a section about installing on that page:

<img width="772" alt="Screenshot 2024-01-17 at 13 28 15" src="https://github.com/wp-cli/handbook/assets/841956/89956eb2-c139-45a8-b274-fa72d443d47d">

Are you suggesting adding an additional sentence to that section for commands like this which aren't bundled with WP-CLI by default?

**Comment by hirasso** [comment]
OMG, you are right! 🫣😄 ...somehow I assumed that the global parameters would be the last bit of information on the page, so I stopped scrolling.

What would you think about moving the Installation instructions up, so that they come before the global parameters?
