### ISSUE TITLE
Markdown files missing in handbook

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/handbook#485]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

In `commands-manifest.json`, few `markdown_source` URLs are not working. Eg:

- `https:\/\/github.com\/wp-cli\/handbook\/blob\/main\/commands\/scaffold\/package-tests.md` [Ref](https://github.com/wp-cli/handbook/blob/efe99b0efbfc42a58f7d26cc5d3f912acf9221e2/bin/commands-manifest.json#L1682) 
- `https:\/\/github.com\/wp-cli\/handbook\/blob\/main\/commands\/scaffold\/package-readme.md` [Ref](https://github.com/wp-cli/handbook/blob/efe99b0efbfc42a58f7d26cc5d3f912acf9221e2/bin/commands-manifest.json#L1679C29-L1679C118)

Is this the reason pages like `https://developer.wordpress.org/cli/commands/scaffold/package-tests/` not showing the docs properly?

**Describe what you would expect as the correct outcome**

Handbook pages should display correct and full command docs.

**Comment by swissspidy** [comment]
The handbook should only contain documentation for bundled commands. `scaffold-package-tests` isn't bundled, so it shouldn't be mentioned in `commands-manifest.json`.

**Comment by ernilambar** [comment]
But we have included other non bundled commands like `profile`, `admin`, etc. Those are kept in the manifest and pages are also populated as expected. Eg: https://developer.wordpress.org/cli/commands/profile/

**Comment by swissspidy** [comment]
Hmm interesting. I don't know where the line was drawn there 🤷 

cc @danielbachhuber @schlessera

**Comment by danielbachhuber** [comment]
I'm open to including the others if we communicate that the package needs to be installed independently.

**Comment by ernilambar** [comment]
Depends upon https://github.com/wp-cli/handbook/issues/507

**Comment by ernilambar** [comment]
This is now unblocked by https://github.com/wp-cli/handbook/issues/507

**Comment by ernilambar** [comment]
It seems those missing scaffold package markdown files are ignored in `.gitignore`.

```
commands/scaffold/package*
```

Ref: https://github.com/wp-cli/handbook/blob/main/.gitignore#L12
