### ISSUE TITLE
Create a "Code Review" document

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/handbook#49]
To better communicate how pull requests are considered, we should create a "Code Review" document explaining code review procedures.

@goldenapples wrote wise words in https://github.com/fusioneng/tech-docs/blob/0d53f3da41e0bec4511f3b4a63e6b4fc528da865/team-culture/code-review.md#what-code-review-is that we can crib from.

**Comment by danielbachhuber** [comment]
@goldenapples Would you want to submit what you've written as a first pass and we can adapt from there?

**Comment by goldenapples** [comment]
Sure! Just posted it at #130. I'll look through the rest of the handbook to find some good point to link to this document. I'm thinking links from "contributing", "pull-requests", and "committers-credo" seem appropriate.

**Comment by danielbachhuber** [comment]
> I'll look through the rest of the handbook to find some good point to link to this document. I'm thinking links from "contributing", "pull-requests", and "committers-credo" seem appropriate.

That'd be great, thanks :)

**Comment by danielbachhuber** [comment]
:shipit:
