### ISSUE TITLE
Full Text not Showing in Common Issues Page

### ISSUE THREAD

**Issue by devmuhib009** [wp-cli/handbook#495]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

If you visit [Common Issues](https://make.wordpress.org/cli/handbook/guides/common-issues/#php-fatal-error-call-to-undefined-function) Page, this is ending with / and after that we had more text on github. We need to add this text.

**Describe how other contributors can replicate this bug**
I will create a pull request to solve it.

**Describe what you would expect as the correct outcome**

Currently the text is: PHP Fatal error: Call to undefined function \
We need to add : **PHP Fatal error: Call to undefined function <WordPress function>**

**Provide a possible solution**

If you happen to have a suggestion on how to fix this bug, please tell us in here.

Just leave this section out if you don't know how to fix it.

**Provide additional context/Screenshots**

![wpcli](https://github.com/wp-cli/handbook/assets/142894870/bc5ae725-44d1-4c93-ad69-386c74e0f26f)

**Comment by ernilambar** [comment]
Completed in https://github.com/wp-cli/handbook/pull/496
