### ISSUE TITLE
handbook-manifest.json shows empty title for how-to-create-custom-plugins

### ISSUE THREAD

**Issue by WinsleyJ** [wp-cli/handbook#541]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

The `handbook-manifest.json` shows an empty title for `how-to-create-custom-plugins`

```json
"how-to-create-custom-plugins": {
   "title": "",
   "slug": "how-to-create-custom-plugins",
   "markdown_source": "https:\/\/github.com\/wp-cli\/handbook\/blob\/main\/how-to-create-custom-plugins.md",
   "parent": null
}
```

It's because the file `how-to-create-custom-plugins.md` doesn't has a title it start with a heading level 2:

```md
## How to create a custom plugin:
```

It should be:
```md
# How to create a custom plugin:
```

And maybe the other headings should also move one level up.

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by WinsleyJ** [comment]
@schlessera Thanks for accepting my first pull request (#542)! The handbook-manifest.json still needs to be generated again, so the title is filled with the correct value. Is this something I can do as well?
