### ISSUE TITLE
Documentation for running tests

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/handbook#57]
Now that the project consists of many sub-components, it's not clear how to (or whether it's necessary to) run all tests for all commands.

Points of note:

* If a contributor makes a change to a command in a sub-component, is it sufficient to run just the tests for that particular sub-component?
* If a contributor makes a change to the bootstrap functionality, how can they run the tests for all of the commands to ensure nothing unexpected breaks?
* The `bin/test.sh` script that lives in every sub-component command has a dependency on the `behat` executable being installed globally. It should instead run Behat from the root `vendor/bin/behat` executable if possible.

Ref: https://make.wordpress.org/cli/handbook/pull-requests/

Related: #17.

**Comment by danielbachhuber** [comment]
👍

**Comment by danielbachhuber** [comment]
While we're in a waiting period to get this into the documentation (blocked on #17):

> If a contributor makes a change to a command in a sub-component, is it sufficient to run just the tests for that particular sub-component?

Yes

> If a contributor makes a change to the bootstrap functionality, how can they run the tests for all of the commands to ensure nothing unexpected breaks?

This will be indirectly handled by https://github.com/wp-cli/phar-build, but we should have explicit documentation for manually achieving the same.

> The `bin/test.sh` script that lives in every sub-component command has a dependency on the `behat` executable being installed globally. It should instead run Behat from the root `vendor/bin/behat` executable if possible.

Not necessarily, as you can set an alias to the root `vendor/bin/behat` too (or add the `vendor/bin` directory to your `$PATH`). With this being said, it'd be easy enough to fall back to the local binary if the global isn't found.

**Comment by dmblack** [comment]
Just some feedback notes on this for the moment. Will hopefully have some time to contribute changes soon.

Test - Prerequisites:
- Behat
- - Mentioned above.
- Contributions
- - Some brief steps on adding tests.
- MySQL
- - Provide details on requirements for service, or
- - Supply docker image preconfigured?
- - Centrally store credentials (Noticed they are stored in several locations)
- php-codesniffer?
- phpunit-environment?

**Comment by danielbachhuber** [comment]
> If a contributor makes a change to the bootstrap functionality, how can they run the tests for all of the commands to ensure nothing unexpected breaks?

I want to reference the repo that performs the full test suite run, but blocked on rename https://github.com/wp-cli/wp-cli/issues/4108#issuecomment-319669752

**Comment by danielbachhuber** [comment]
🔨
