### ISSUE TITLE
Released vs `master` documentation

### ISSUE THREAD

**Issue by schlessera** [wp-cli/handbook#58]
The handbook is currently being generated against the latest `master` versions. This causes issues where the handbook documents functionality that has not been released yet, like in https://github.com/wp-cli/media-command/issues/15

We should discuss how to best handle this. I see three general approaches that are commonly being used for such documentation:

1. Always build handbook against latest released versions only, so that the handbook does not contain stuff that is not generally available yet. This is the easiest approach, and is a safe compromise.

2. Build two separate versions of the handbook (`stable`|`nightly` or similar), that the users can switch to and from as needed. This covers most use cases.

3. Build the handbook for every released version + `master` (`0.23.0`|`1.0.0`|`1.1.0`|`nightly` or similar), that the users can switch from. This is the complete solution that  makes sure that even users that rely on legacy versions get reliable documentation.

**Comment by schlessera** [comment]
Related: https://github.com/wp-cli/ideas/issues/43

**Comment by danielbachhuber** [comment]
> Always build handbook against latest released versions only, so that the handbook does not contain stuff that is not generally available yet. This is the easiest approach, and is a safe compromise.

Historically, this is what we've always done, and I think is reasonable to do going forward.

The reason the handbook is built against the current master (or at least, current as of a few weeks ago), is that I neglected to switch to a tagged release when I generated the docs.

**Comment by danielbachhuber** [comment]
This issue is no longer applicable, as the docs represent the latest tagged release.
