### ISSUE TITLE
Document the aliases feature on the config page

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/handbook#73]
From Slack:

> I've read a lot of articles and watched videos from WCs.  Wondering as a hoster with multiple sites, how I would target those installs (spread across different cpanel /home/* directories) to install and activate a plugin.  The plugin commands are straightforward, but what I'm not clear on (and don't find in docs) is _if I can target those WordPress installs from a global WP-CLI install_, and how I would do that.  Thanks.

WP-CLI aliases are a good fit for this: https://github.com/wp-cli/wp-cli/issues/2039#issuecomment-230478817

Our annotated `wp-cli.yml` file makes them hidden though:

![image](https://user-images.githubusercontent.com/36432/27399599-291a17ee-5672-11e7-8d9f-4717714bf903.png)

We should document aliases in a dedicated sub-section.

**Comment by jimlongo56** [comment]
Also please explain the use of `user`, `url`, `path`, `ssh` and `http`.

**Comment by jimlongo56** [comment]
Note also `proc_open()`, and `proc_close()` are required for proper execution of `@all`

I got caught up with both of those being in `disable_functions` in `php.ini`

**Comment by schlessera** [comment]
Done via #89
