### ISSUE TITLE
WP_CLI\Utils\wp_clear_object_cache() is missing from handbook documentation

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/handbook#78]
It's missing because it's in `utils-wp.php`, which isn't loaded until after WordPress is loaded. `wp handbook api-dump` is run before WordPress is loaded.

**Comment by mikeschinkel** [comment]
Then the docs needs to be updated to include `--prompt`.  :-)

**Comment by danielbachhuber** [comment]
@mikeschinkel Can you create a separate issue please?
