### ISSUE TITLE
Mention and document use of `tee` in "Save command output" section of Shell friends

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/handbook#79]
`tee` is a useful utility if you want to capture _and_ display output from a command. We should mention it, and document its usage, in the "Save command output" section.

https://github.com/wp-cli/handbook/blob/master/shell-friends.md 

From https://github.com/zao-web/cli-framework/issues/5#issuecomment-311663888

**Comment by kouratoras** [comment]
I submitted a PR for this:
https://github.com/wp-cli/handbook/pull/80
